image: node:8.1.2

pipelines:
  default:
    - step:
        name: "Deploy to production"
        deployment: production
        script:
          - ssh -T root@104.131.28.152
          - bash deploy.sh
