image: node:8.1.2

pipelines:
  default:
    - step:
        name: "Deploy to production"
        deployment: production
        script:
          - mkdir -p ~/.ssh
          - cat known_hosts >> ~/.ssh/known_hosts
          - (umask 077; echo $MY_SSH_KEY | base64 --decode > ~/.ssh/id_rsa)
          - echo "Deploy finished"
